name: Daily RDS Update

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: 

jobs:
  autoscrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.2'
          use-public-rspm: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

      - name: Install packages manually
        run: |
          Rscript -e 'install.packages(c("rvest", "fuzzyjoin", "stringr", "dplyr", "jsonlite", "lubridate", "tibble", "remotes"), repos="https://cloud.r-project.org")'
        
      - name: Install oddsapiR
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: Rscript -e 'remotes::install_github("sportsdataverse/oddsapiR", upgrade = "never")'
        
      - name: Run script
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: Rscript run_daily.R 

      - name: Commit and Push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add HistScoresGit.rds
          git commit -m "Daily data update" || echo "No changes to commit"
          git push
