name: Daily RDS Update

on:
  schedule:
    # This runs at 00:00 UTC every day. 
    # Use 'crontab.guru' to change the timing if needed.
  - cron: '0 12 * * *'
  workflow_dispatch: # This allows you to run it manually for testing

jobs:
  autoscrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.2'
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          cache-version: 4
          packages: |
            rvest
            fuzzyjoin
            stringr
            dplyr
            jsonlite
            lubridate
            tibble
            remotes
          # Note: No 'upgrade: true' or extra 'true' lines here to avoid the R error

      - name: Install oddsapiR manually
        run: Rscript -e 'remotes::install_github("sportsdataverse/oddsapiR")'
        
      - name: Run script
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: Rscript run_daily.R # REPLACE with your actual file name

      - name: Commit and Push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add HistScoresGit.rds
          git commit -m "Daily data update" || echo "No changes to commit"
          git push

     
