name: Daily RDS Update

on:
  schedule:
    # This runs at 00:00 UTC every day. 
    # Use 'crontab.guru' to change the timing if needed.
  - cron: '0 0 * * *'
  workflow_dispatch: # This allows you to run it manually for testing

jobs:
  autoscrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            rvest
            fuzzyjoin
            stringr
            dplyr
            jsonlite
            oddsapiR
            lubridate
            tibble

        
      - name: Run script
        run: Rscript run_daily.R # REPLACE with your actual file name

      - name: Commit and Push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add HistScores.rds
          git commit -m "Daily data update" || echo "No changes to commit"
          git push

     
